# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [1]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

def func(arr):
    return arr[0]==arr[(len(arr)-1)]
# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True
print(func(numbers_x))
print(func(numbers_y))
# numbers_y = [75, 65, 35, 75, 30]
# result is False

True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [2]:
import numpy as np


array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

addition_result = array1 + array2
print("Element-wise addition result:")
print(addition_result)

product_result = array1 * array2
print("\nElement-wise product result:")
print(product_result)


Element-wise addition result:
[[ 8 10 12]
 [14 16 18]]

Element-wise product result:
[[ 7 16 27]
 [40 55 72]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [6]:
array=np.arange(0,12)
array=array.reshape(3,4)
print(array)
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

horizontal_concatenation = np.concatenate((array1, array2), axis=1)
print("Horizontal concatenation:")
print(horizontal_concatenation)

vertical_concatenation = np.concatenate((array1, array2), axis=0)
print("\nVertical concatenation:")
print(vertical_concatenation)

Horizontal concatenation:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Vertical concatenation:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [13]:
shopping_cart = {
    "Bread": 0,
    "Milk": 0,
    "Eggs": 0,
    "Cheese": 0,
    "Apples": 0,
    "Bananas": 0,
    "Chicken": 0,
    "Rice": 0,
}

print("Welcome to Online Shopping Cart")
print("Available items:")
for item in shopping_cart:
    print("-", item)

while True:
    item_name = input("\nEnter the name of the item you want to add (or 'q' to quit): ").capitalize()
    
    if item_name == 'Q':
        break
    
    if item_name in shopping_cart:
        quantity = int(input("Enter the quantity: "))
        shopping_cart[item_name] += quantity
        print(f"{quantity} {item_name}(s) added to the cart.")
    else:
        print("Invalid item! Please enter a valid item name.")

print("\nShopping Cart Contents:")
for item, quantity in shopping_cart.items():
    if quantity > 0:
        print(f"- {quantity} {item}(s)")

print("\nThank you for shopping with us! Goodbye.")


Welcome to Online Shopping Cart
Available items:
- Bread
- Milk
- Eggs
- Cheese
- Apples
- Bananas
- Chicken
- Rice
2 Bread(s) added to the cart.
3 Milk(s) added to the cart.
Invalid item! Please enter a valid item name.

Shopping Cart Contents:
- 2 Bread(s)
- 3 Milk(s)

Thank you for shopping with us! Goodbye.


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [19]:
def classify_emails(emails):
    important_keywords = ["urgent", "important", "action required"]
    promotions_keywords = ["deal", "promotion", "discount"]
    spam_keywords = ["lottery", "inheritance", "bol"]

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        email_lower = email.lower()
        
        if any(keyword in email_lower for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in email_lower for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in email_lower for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

# Example list of emails
example_emails = [
    "Important: Action Required",
    "Great Deals Inside: Get 50% Off!",
    "You've Won a Lottery!",
    "Urgent: Please Respond ASAP",
    "Inheritance Notification",
    "Limited Time Offer: Big Discounts",
    "Bol news say shazir baat kr rha hu "
]

important, promotions, spam = classify_emails(example_emails)

print("Important Emails:")
print('\n'.join(important))
print("\nPromotions Emails:")
print('\n'.join(promotions))
print("\nSpam Emails:")
print('\n'.join(spam))


Important Emails:
Important: Action Required
Urgent: Please Respond ASAP

Promotions Emails:
Great Deals Inside: Get 50% Off!
Limited Time Offer: Big Discounts

Spam Emails:
You've Won a Lottery!
Inheritance Notification
Bol news say shazir baat kr rha hu 


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [21]:

translations = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    'Yes':'Si',
    'Of course':'Ciaro'
}


def translate_word(word):
    if word in translations:
        return translations[word]
    else:
        return "Translation not available"

while True:
    english_word = input("Enter an English word (or 'q' to quit): ").lower()
    if english_word == 'q':
        break
    translation = translate_word(english_word)
    print(f"The Spanish translation of '{english_word}' is: {translation}\n")


The Spanish translation of '1' is: Translation not available



# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [22]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv")
df

C:\Users\abdul\AppData\Local\Temp\ipykernel_22552\3298459906.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [24]:
total_global_sales = df["Global_Sales"].sum()
total_global_sales

8920.44

In [25]:
highest_global_sales_game = df.loc[df["Global_Sales"].idxmax()]
print("Game with the highest global sales:")
print(highest_global_sales_game)

Game with the highest global sales:
Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object


In [26]:
average_sales = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].mean()
print("Average sales for each region:")
print(average_sales)

Average sales for each region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [27]:
top_genres = df.groupby("Genre")["Global_Sales"].sum().nlargest(5)
print("Top 5 most popular game genres based on global sales:")
print(top_genres)

Top 5 most popular game genres based on global sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [28]:
total_sales_genre_region = df.groupby("Genre")[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].sum()
most_popular_genre_na = total_sales_genre_region["NA_Sales"].idxmax()
print("Most popular genre in North America:", most_popular_genre_na)


Most popular genre in North America: Action


In [31]:
print("Last 10 rows:")
df.tail(10)

Last 10 rows:


Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [30]:
top_platforms = df.groupby("Platform")["Global_Sales"].sum().nlargest(3)
print("Top 3 gaming platforms with the highest global sales:")
print(top_platforms)

Top 3 gaming platforms with the highest global sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [32]:
genre_market_share = df.groupby("Genre")["Global_Sales"].sum() / total_global_sales * 100
print("Market share for each genre:")
print(genre_market_share)

Market share for each genre:
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [33]:
correlation_coefficient = df["NA_Sales"].corr(df["EU_Sales"])
print("Correlation coefficient between NA_Sales and EU_Sales:", correlation_coefficient)

Correlation coefficient between NA_Sales and EU_Sales: 0.767726748370263
